spring.application.name=eurekaserver
spring.security.basic.enabled=true
spring.security.user.name=curso-ms-eureka-user
spring.security.user.password=elkfdakldlfdafd35465

server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false